### ISSUE TITLE
Missing event type in events

### ISSUE THREAD

**Issue by smartiniOnGitHub** [jenkinsci/statistics-gatherer-plugin#23]
Hi all,
would it be (very) useful to have in any event even an attribute like 'eventType' that specify the kind/category of event (build, job, scm, etc) ...
What do you think ?

Last, in comparison with [CloudEvents Spec](https://github.com/cloudevents/spec/blob/master/json-format.md#2-attributes) maybe even other envelope fields could be useful too (like 'eventTime' and maybe even 'jenkinsEventsVersion'), but this could be another story ... you want to discuss in a different issue ?

Thanks a lot, Sandro

**Comment by andrewrch** [comment]
Since you can configure a URL for each type, you can use a different endpoint to differentiate.

E.g. 

domain.com/stats/scm
domain.com/stats/job

Etc

**Comment by smartiniOnGitHub** [comment]
Ok, thanks for the info, I wasn't aware. I'l try that way in the meantime. Bye
