### ISSUE TITLE
No request received

### ISSUE THREAD

**Issue by giddel** [jenkinsci/statistics-gatherer-plugin#32]
After install the plugin (v2.0.3) and configure the target URLs - nothing happens.
I cannot see any request from Jenkins on the target site. And yes, I've checked the targets with manual test requests.
How I can see, if the plugin is working correctly and it fires?
How can I find out, what goes wrong?
Are there special needs to the pipelines to trigger the plugin?

**Comment by m0ises2** [comment]
Hey, any updates on this?

**Comment by m0ises2** [comment]
![image](https://user-images.githubusercontent.com/7365392/60826171-edd4ca00-a172-11e9-9c65-a6c668fab23d.png)

**Comment by kyanh-vX7HLAHZLPsUxeHD** [comment]
This setting is hidden in `advanced settings` tab :D

**Comment by giddel** [comment]
Ok, I've found the checkbox...
I thought, this checkbox is for overriding the https protocol by unsafe http.
UI rulez ...
Thanks!
